AboutLabel: About
AboutPageLabel: About De Calixtinus
AboutPageTitle: De Calixtinus
AcceptDisclaimerLabel: I accept use of cookies and testing status
AcceptDisclaimerRequired: You must accept the conditions before proceeding
AcceptLabel: Accept
AccessTitle: Access
AccessibleTitle: Accessible
AccommodationLabel: Accommodation
AccommodationPenanceLabel: Accommodation
AccommodationPreferencesLabel: Accommodation Preferences
AddressTitle: Address
AfterText: after
AirportDescription: An airport, airfield or aerodrome
AirportTitle: Airport
AlwaysOpenLabel: Always Open
AppName: De Calixtinus
ArduousDayLabel: Arduous Day
ArtworkDescription: A piece of art
ArtworkTitle: Art
AscentLabel: Ascent
AscentMsg ascent@Float: Ascent ^{formatHeight sou ascent}
AustereTitle: Austere
BackLabel: Back
BankTitle: Bank
BarrierTitle: Barrier
BeachDescription: A beach (sea or river)
BeachTitle: Beach
BedlinenTitle: Bedlinen
BeforeText: before
BicycleRepairTitle: Bicycle Repair
BicycleStorageTitle: Bicycle Storage
BoatTitle: Boat/Canoe (paddled)
BreakfastTitle: Breakfast
BridgeDescription: A bridge acting as a waypoint or point of interest
BridgeTitle: Bridge
BusTitle: Bus
CalendarTitle: Calendar
CaminoLabel: Camino
CaminoSelectTitle: Select Camino
CaminosLabel: Caminos
CaminoText: Select the Camino you wish to walk from the following options. Many caminos have variations and alternative routes that you can choose on the next screen.
CampGroundTitle: Camping Ground
CampingTitle: Camping
CampSiteTitle: Camp-site
CasaRuralTitle: Casa Rural/Quinta
CasualTitle: Casual
CathedralDescription: A cathedral, basillica, shrine or other large religious building
CathedralTitle: Cathedral
ChainsLabel: Chains
ChurchDescription: A church or chapel
ChurchTitle: Church
CityDescription: A large urban area with multiple options for services and accommodation
CityTitle: City
ClosedDayLabel region@Text: Closed Day (^{renderLocalisedRegion config sou locales region})
ClosedDayText: Closed Day
ClosedText: closed
CloseLabel: Close
ComfortableTitle: Comfortable
ComfortLabel: Comfort
CopyLinkTitle: Copy Link
CrossDescription: A roadside crucifix
CrossTitle: Cross
CulturalPoiTitle: Cultural
CyclingTitle: Cycling
CyclePathTitle: Cycle Path (bicycles only)
DailyLabel: Daily
DateLabel: Date
DateMsg day@C.Day: <span .date>^{renderLocalisedDate sou True locales day}
DateRangeMsg day1@C.Day day2@C.Day:
<span .date-range>
  $if day1 == day2
    ^{renderLocalisedDate sou True locales day1}
  $else
    ^{renderLocalisedDate sou True locales day1} - ^{renderLocalisedDate sou True locales day2}
DayLabel: Day
DayOfMonthName dom@C.DayOfMonth: #{dom}
DayOfWeekName dow@C.DayOfWeek: ^{renderLocalisedTime sou locales "%a" dow}
DaysElapsedMsg days@Int: #{sformat int days} days total
DayServicePreferencesLabel: Preferred Services during Day
DayServicesPenanceLabel: Missing Services (Day)
DaysWalkingMsg days@Int: #{sformat int days} days walking
DayText: day
DescentLabel: Descent
DescentMsg descent@Float: Descent ^{formatHeight sou descent}
DinnerTitle: Dinner
DirectionsTitle: Directions
DistanceAdjustLabel: Distance Adjustment
DistanceFormatted distance@Float: ^{formatDistance sou distance}
DistanceLabel: Distance
DistanceMsg actual@Float effort@Float transport@Float perceived@(Maybe Float): Distance ^{formatDistance sou actual} #
 (feels like ^{formatMaybeDistance sou perceived}#
 $if transport > 0
   \, transport ^{formatDistance sou transport}#
 \)
DistancePenanceLabel: Distance
DistancePreferencesLabel: Distance Preferences (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DistancePreferencesPerceivedLabel: Perceived Distance Preferences (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DoubleTitle: Double
DoubleWcTitle: Double with WC
DownloadKmlTitle: Download KML
DownloadSpreadsheetTitle: Download Spreadsheet
DryerTitle: Dryer
EasyMode: Easy Mode
EasyModeText: Easy mode reduces the number of choices that you have to make and chooses sensible defaults for most things.
ElevationFormatted elev@Float: ^{formatHeight sou elev}
ElevationLabel: Elevation (#{U.unitSymbol (U.preferredUnit sou U.Elevation)})
EventsLabel: Events
ExceptText: except
ExcludedLabel: Locations not to stop at
ExcludedStopsLabel: Excluded Stops
FailureLabel: Failure
FarmlandDescription: Farmland, greenhouses, pasture etc.
FarmlandTitle: Farmland
FatiguePenanceLabel: Fatigue
FerryTitle: Ferry
FestivalEventTitle: Festival
FinishDateLabel: Finish Date
FinishLocationLabel: Trip End
FitnessLabel: Fitness
FitTitle: Fit
FoodEventTitle: Food
ForbiddenStopsLabel: Forbidden Stops
FountainDescription: A fountain or spring, either a large decorative fountain or a source of water
FountainTitle: Fountain
FromLabel: From
FrugalTitle: Frugal
GiteTitle: Gîtes d'Étape
GroceriesTitle: Groceries
GuestHouseTitle: Guesthouse
HalfBoardTitle: Half-Board
HandwashTitle: Handwash
HardDayLabel: Hard Day
HazardDescription: A road crossing, bridge, slope etc. that needs to be treated with caution
HazardTitle: Hazard
HeatingTitle: Heating
HelpLabel: Help
HelpPageTitle: General Help
HelpPopupTitle: Help
HistoricalDescription: A historical site, archaeological site, ruin or other historical point of interest
HistoricalPoiTitle: Historical
HistoricalTitle: Historical site
HolidayEventTitle: Holiday
HolidaysLabel: Holidays
HomePageLabel: Home
HomePageText1: Welcome to De Calixtinus.
HomePageText2: If you are planning to walk the Camino Santiago, this site allows you to develop a set of daily stages tailored to your level of fitness and preferences in terms of accommodation, food etc. The panner is designed to give you a globally optimal set of stages, stretching some a bit and reducing others, to give you the best overall trip.
HomePageText3: To begin, press the Start button below.
HomeStayTitle: Home Stay
HostelTitle: Hostel
HotelTitle: Hotel
HoursTitle: Hours
HouseTitle: House
IdentifierLabel: ID
IndustryDescription: An industrial estate or large factory
IndustryTitle: Industrial
InformationDescription: Information on the source data used when generating this plan.
InformationLabel: Information
InformationPointDescription: A local tourist office, guide, etc. not specifically geared towards pilgrims
InformationPointTitle: Information Point
InformationTitle: Information
IntersectionDescription: A road or path intersection
IntersectionTitle: Intersection
InvalidCamino: Invalid camino
InvalidStep: Invalid preferences step
JourneyLabel: Journey
JunctionDescription: The branch or join point for two routes or two caminos
JunctionTitle: Junction
KeyLabel: Key
KitchenTitle: Kitchen
LatitudeLabel: Latitude
LegendLabel: Legend
LegPenanceMsg pen@Penance: +^{formatPenance sou True pen}
LinkTitle locd@(Localised TaggedURL) defd@(Localised TaggedText): $if hasLocalisedText locales locd
  ^{renderLocalisedText locales True True False locd}
$else
  ^{renderLocalisedText locales True True False defd}
LinkOut: More information
ListMsg msgs@[CaminoMsg]: <ul .comma-separated-list>
  $forall m <- msgs
    <li>^{renderCaminoMsg config sou locales m}
LocationLabel: Location
LocationPenanceLabel: Location
LocationPreferencesLabel: Location Preferences
LocationsLabel: Locations
LockersTitle: Lockers
LongitudeLabel: Longitude
LookoutDescription: A lookout or scenic view
LookoutTitle: Lookout
LuxuriousTitle: Luxurious
MapLabel: Map
MapTitle: Map of all Caminos
MassEventTitle: Mass
MattressTitle: Mattress
MedicalTitle: Medical
MetricLabel: Metric Conversion
MetricTitle: Metric/Imperial Conversion
MiscPenanceLabel: Other
MonasteryDescription: A monastery or cloister, often with a hospice attached
MonasteryTitle: Monastery
MonthOfYearName moy@C.MonthOfYear: ^{renderLocalisedMonth sou locales moy}
MoreInformation: More Information
MunicipalDescription: A town square, market place, town hall or other municipal building
MunicipalTitle: Municipal
MuseumDescription: A museum or art gallery
MuseumTitle: Museum/gallery
MusicEventTitle: Music
NamedCalendarLabel key@Text: ^{renderLocalisedText locales False False False (getCalendarName config key)}
NaturalDescription: A nature park or area of natural beauty, as well as large landscape features such as mountains
NaturalPoiTitle: Natural
NaturalTitle: Nature park
NextLabel: Next
NormalTitle: Normal
NotesLabel: Notes
NthWeekdayText wom@WeekOfMonth dow@C.DayOfWeek: ^{renderLocalisedWeekOfMonth sou locales wom} ^{renderLocalisedDayOfWeek sou locales dow}
OpenHoursTitle: Open Hours
OpenText: open
OrdinalAfterWeekday nth@Int dow@C.DayOfWeek: ^{renderLocalisedOrdinal sou locales (abs nth)} ^{renderLocalisedDayOfWeek sou locales dow} #{renderLocalisedBeforeAfter nth "before" "after"}
OrdinalBeforeAfter nth@Int unit@CaminoMsg: ^{renderLocalisedOrdinal sou locales (abs nth)} ^{renderCaminoMsg config sou locales unit} ^#renderLocalisedBeforeAfter nth  "before" "after"}
OtherLabel: Other
ParkDescription: A park or garden
ParkTitle: Park
PathLabel: Path
PeakDescription: A peak or mountain pass
PeakTitle: Peak/pass
PenanceFormatted showZero@Bool pen@Penance: ^{formatPenance sou showZero pen}
PenanceFormattedPlain showZero@Bool pen@Penance: ^{formatPenancePlain sou showZero pen}
PenanceMsg pen@Penance: Penance ^{formatPenance sou True pen}
PenanceReject: Rejected
PenanceSummaryLabel: Penance
PerceivedDistanceLabel: Perceived Distance
PerformanceEventTitle: Performance
PersistentLinkTitle: Persistent Link
PetsTitle: Pets
PharmacyTitle: Pharmacy
PilgrimageLabel: Pilgrimage
PilgrimAlbergueTitle: Pilgrim Albergue
PilgrimMassEventTitle: Pilgrim's Mass
PilgrimPoiTitle: Pilgrim
PilgrimResourceDescription: A pilgrim's office, rest point, etc. specifically geared towards pilgrims
PilgrimResourceTitle: Pilgrim Resource
PilgrimTitle: Pilgrim
PlaceholderLabel: Placeholder
PlanKmlLabel: Plan (KML)
PlanKmlTitle: Generate a plan as a KML file suitable for Google Earth
PlanLabel: Plan
PlanTitle: Generate a plan and display it
PlanXlsxLabel: Plan (Xlsx)
PlanXlsxTitle: Generate a plan as a Xslx file suitable for spreadsheet applications
PoiDescription: A generic waypoint or point of interest
PoiLabel: Point of Interest
PoiPreferencesTitle: Point of Interest Preferences
PoisLabel: Points of Interest
PoiText: Select the significant point of interests that you intend to stop at while travelling. These stops will be built into the planning time.
PoiTitle: Locality
PoolTitle: Pool
PrayerTitle: Prayer
PreferencesLabel: Preferences
PreferredRestPointsLabel: Preferred Rest Points
PrivateAlbergueTitle: Private Albergue
ProgramLabel: Program
PromontoryDescription: A promontory, cliff or headland
PromontoryTitle: Promontory/Headland
PublicHolidayLabel region@Text: Public Holiday ^{renderLocalisedRegion config sou locales region}
PublicHolidayText: Public Holiday
QuadrupleTitle: Quadruple
QuadrupleWcTitle: Quadruple with WC
RangeTitle: Distance and Time Preferences
RangeText: Select the ranges that you will accept for both distance travelled over a day (in km) and time taken (in hours) for each day. Also select the range for how many days you wish to travel before resting. The ranges are absolute minimum, preferred lower bound, target, preferred upper bound and absolute maximum.
RefugeTitle: Refuge
RegionLabel: Region
RegionsLabel: Regions
RecreationPoiTitle: Recreation
ReligiousEventTitle: Religious Ceremony
ReligiousPoiTitle: Religious
RequiredStopsLabel: Required Stops
RestaurantTitle: Restaurant
RestDaysLabel: Rest Days
RestLocationPreferencesLabel: Rest Location Preferences
RestPenanceLabel: Rest
RestpointLabel: Rest Point
RestpointsLabel: Rest Points
RestPointsPenanceLabel: Rest Points
RestPreferencesLabel: Rest Preferences (#{U.unitSymbol (U.preferredUnit sou U.Calendar)})
RestPressureLabel: Rest Pressure (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
RestPressurePenanceLabel: Rest Pressure
RestServicePreferencesLabel: Rest Services
RoadTitle: Road/path
RouteLabel: Route
RoutePreferencesLabel: Routes
RouteServicesPreferencesLabel: Missing Services on Route
RoutesLabel: Routes
RoutesText: Select the route variants that you wish to walk. The standard route is always selected. Some routes require other routes or cannot be done in conjunction with other routes.
RoutesTitle: Select Routes
SelectCamino: Select a camino
SelectComfort: Select a comfort level
SelectFitness: Select a fitness level
SelectPoiCategories: Select points of interest that you might visit
SelectTravel: Select a travel type
SelectUnits: Select units
ServicesLabel: Services
ServicesPreferencesLabel: Missing Services
ServicesRestText: Select the location, accomodation and services preferences for a rest stop. Rest stops are places where you can take a day off to recover, replenish, see the sights and generally get ready for the next stage of the walk.
ServicesRestTitle: Select Rest Stop Preferences
ServicesStockText: Select the location, accomodation and services preferences for a "stock-up" day". Stock-up days are where you expect to not have many facilities over the next day, because many of the services you would want will be closed. For example, if the next day is a Sunday or a public holiday, you will need to ensure that you have food pre-bought.
ServicesStockTitle: Select Stop Preferences for a Stock-up Day
ServicesStopText: Select the location, accomodation and services preferences for the end of the day.
ServicesStopTitle: Select the Day's Travel Preferences
ServicesText2: All preferences are measured in kilometres of walking and represent the amount of extra distance you would walk to get something you want.
SharedTitle: Shared
ShopDescription: A shop of note or usefulness
ShopTitle: Shop
ShowLabelsTitle: Show camino and route labels on map
ShowOnMapTitle: Show on map
ShowPreferencesText: If you are happy with these preferences, you can generate a plan. Otherwise, use the Back button to change your choices.
ShowPreferencesTitle: Review Preferences
SingleTitle: Single
SIUnitsTitle: Kilometres, metres, hours
SleepingBagTitle: Sleeping Bag
StablesTitle: Stables
StageLabel: Stage
StagesMsg stages@Int: ^{formatStages stages}
StartDateLabel: Start Date
StartLabel: Start!
StartLocationLabel: Start Location
StartText: Select the start location and finish location for your trip.
StartTitle: Start and Finish Points
StationDescription: A train or bus station
StationTitle: Station
StatueDescription: A statue, bas-relief, etc.
StatueTitle: Statue
StockpointLabel: Stocking Point
StopLabel: Stop
StopPenanceLabel: Stop
StopPreferencesLabel: Missing Services (Stop)
StopPreferencesText: Day's end represents the business of stopping and settling down for the night.
StopServicePreferencesLabel: Preferred Services at Day's End
StopServicesPenanceLabel: Missing Services (Stop)
StopsLabel: Locations to stop at
StopsText: Select locations where you must stop at the end of a day and locations that you do not wish to stop at.
StopsTitle: Required and Excluded Stops
SuggestedLabel: Suggested
SuperFitTitle: Super-fit
TableLabel: Table
TestMessage: Currently under testing, see the About page
TheatreDescription: A theatre, opera house or concert hall
TheatreTitle: Theatre
Time time@TimeOfDay: ^{renderLocalisedTime sou locales "%H%M" time}
TimeAdjustLabel: Time Adjustment
TimeFormatted time@Float: ^{formatHours sou time}
TimeLabel: Time
TimeMsg mtime@(Maybe Float) meffort@(Maybe Float) mtransport@(Maybe Float) mpoi@(Maybe Float): over ^{formatMaybeHours sou mtime} #
  $case (mtransport, mpoi)
    $of (Nothing, Nothing)
    $of (Just t, Nothing)
      \ (transport ^{formatHours sou t})
    $of (Nothing, Just p)
      \ (stops ^{formatHours sou p})
    $of (Just t, Just p)
      \ (transport ^{formatHours sou t}, stops ^{formatHours sou p})
TimePenaltyLabel: Time Penalty
TimePreferencesLabel: Time Preferences (#{U.unitSymbol (U.preferredUnit sou U.Time)})
ToggleDetailTitle: Show/hide additional detail
ToLabel: To
TowelsTitle: Towels
TownDescription: A larger locality with most services and a variety of accommodation usually available
TownTitle: Town
TrailTitle: Trail (walkers only)
TrainTitle: Train
TransportLinksLabel: Transport Links
TransportLinks: Use Transport Links
TransportLinksText: Allow the use of public transport to nearby accommodation and services
TravelBottom: Be careful with fitness. Normal is normal for a young walker with plenty of training; someone who can walk three hours at 5km/hr without tiring. If you have any doubts, choose Unfit.
TravelLabel: Travel Estimation
TravelText1: To begin with, choose the way you intend to travel. Then choose the level of fitness that you have.
TravelText2: Easy mode allows you to fill out a few fields about your travel style and which routes you want to travel. Sensible defaults are then used for things like daily distance, accommodation preferences, must-see stops and the like. Detailed mode allows you to fine-tune your preferences in terms of distance, accommodation, where to stop and so on. However, the level of detail can be quite complex. Use easy mode to start with and then uncheck this box to allow more detail once you are familiar with the system.
TravelTitle: Travel Style and Fitness
TripFinishLabel: Trip Finish
TripStartLabel: Trip Start
TripleTitle: Triple
TripleWcTitle: Triple with WC
Txt locd@(Localised TaggedText): ^{renderLocalisedText locales False False False locd}
TxtPlain attr@Bool js@Bool locd@(Localised TaggedText): ^{renderLocalisedText locales True attr js locd}
TypeLabel: Type
UnfitTitle: Unfit
UnitsLabel: Units
UnusedLabel: Unused
USUnitsTitle: Miles, feet, hours
VeryFitTitle: Very fit
VeryUnfitTitle: Very unfit
VillageDescription: A smaller locality with limited, or no, services and accommodation
VillageTitle: Village
WalkingNaismithTitle: Walking (strong walkers)
WalkingTitle: Walking
WarningsLabel: Warnings
WarningTitle: Warning
WashingMachineTitle: Washing Machine
WaterBodyDescription: Lake, reservoir, river, canal, etc.
WaterBodyTitle: Water
WaypointLabel: Waypoint
WharfDescription: A wharf, quay or pier connecting to a boat
WharfTitle: Wharf
WiFiTitle: WiFi
WineryDescription: A winery or port warehouse
WineryTitle: Winery

