AboutLabel: About De Calixtinus
AboutTitle: De Calixtinus
AcceptLabel: Accept
AccommodationPreferencesLabel: Accommodation Preferences
AcceptDisclaimerLabel: I accept use of cookies and testing status
AcceptDisclaimerRequired: You must accept the conditions before proceeding
AppName: De Calixtinus
BackLabel: Back
CaminosLabel: Caminos
CaminoText: Select the Camino you wish to walk from the following options. Many caminos have variations and alternative routes that you can choose on the next screen.
CaminoTitle: Select Camino
CloseLabel: Close
DayServicePreferencesLabel: Preferred Services during Day
DistancePreferencesLabel: Distance Preferences (km)
EasyMode: Easy Mode
EasyModeText: Easy mode reduces the number of choices that you have to make and chooses sensible defaults for most things.
ExcludedLabel: Locations not to stop at
FinishLocationLabel: Trip End
ForbiddenStopsLabel: Forbidden Stops
HelpLabel: Help
HelpTitle: General Help
HomeLabel: Home
HelpPopupTitle: Help
HomeText1: Welcome to De Calixtinus.
HomeText2: If you are planning to walk the Camino Santiago, this site allows you to develop a set of daily stages tailored to your level of fitness and preferences in terms of accommodation, food etc. The panner is designed to give you a globally optimal set of stages, stretching some a bit and reducing others, to give you the best overall trip.
HomeText3: To begin, press the Start button below.
InvalidCamino: Invalid camino
InvalidStep: Invalid preferences step
LocationPreferencesLabel: Location Preferences
MapLabel: Map
MapTitle: Map of all Caminos
MetricLabel: Metric Conversion
MetricTitle: Metric/Imperial Conversion
MoreInformation: More Information
NextLabel: Next
PlanKmlLabel: Plan (KML)
PlanKmlTitle: Generate a plan as a KML file suitable for Google Earth
PlanLabel: Plan
PlanTitle: Generate a plan and display it
PlanXlsxLabel: Plan (Xlsx)
PlanXlsxTitle: Generate a plan as a Xslx file suitable for spreadsheet applications
PoisLabel: Points of Interest
PoiTitle: Point of Interest Preferences
PoiText: Select the significant point of interests that you intend to stop at while travelling. These stops will be built into the planning time.
PreferredRestPointsLabel: Preferred Rest Points
RangeTitle: Distance and Time Preferences
RangeText: Select the ranges that you will accept for both distance travelled over a day (in km) and time taken (in hours) for each day. Also select the range for how many days you wish to travel before resting. The ranges are absolute minimum, preferred lower bound, target, preferred upper bound and absolute maximum.
RequiredStopsLabel: Required Stops
RestLocationPreferencesLabel: Rest Location Preferences
RestPreferencesLabel: Rest Preferences (days travelled)
RestPressureLabel: Rest Pressure
RestServicePreferencesLabel: Rest Services
RoutePreferencesLabel: Routes
RoutesText: Select the route variants that you wish to walk. The standard route is always selected. Some routes require other routes or cannot be done in conjunction with other routes.
RoutesTitle: Select Routes
SelectCamino: Select a camino
SelectComfort: Select a comfort level
SelectFitness: Select a fitness level
SelectPoiCategories: Select points of interest that you might visit
SelectTravel: Select a travel type
ServicesRestText: Select the location, accomodation and services preferences for a rest stop. Rest stops are places where you can take a day off to recover, replenish, see the sights and generally get ready for the next stage of the walk.
ServicesRestTitle: Select Rest Stop Preferences
ServicesStockText: Select the location, accomodation and services preferences for a "stock-up" day". Stock-up days are where you expect to not have many facilities over the next day, because many of the services you would want will be closed. For example, if the next day is a Sunday or a public holiday, you will need to ensure that you have food pre-bought.
ServicesStockTitle: Select Stop Preferences for a Stock-up Day
ServicesStopText: Select the location, accomodation and services preferences for the end of the day.
ServicesStopTitle: Select the Day's Travel Preferences
ServicesText2: All preferences are measured in kilometres of walking and represent the amount of extra distance you would walk to get something you want.
ShowPreferencesText: If you are happy with these preferences, you can generate a plan. Otherwise, use the Back button to change your choices.
ShowPreferencesTitle: Review Preferences
StartDateLabel: Start Date
StartLabel: Start!
StartLocationLabel: Trip Start
StartText: Select the start location and finish location for your trip.
StartTitle: Start and Finish Points
StopPreferencesLabel: Day's End
StopPreferencesText: Day's end represents the business of stopping and settling down for the night.
StopServicePreferencesLabel: Preferred Services at Day's End
StopsLabel: Locations to stop at
StopsText: Select locations where you must stop at the end of a day and locations that you do not wish to stop at.
StopsTitle: Required and Excluded Stops
SuggestedLabel: Suggested
TestMessage: Currently under testing, see the About page
TimePreferencesLabel: Time Preferences (hours)
TransportLinks: Use Transport Links
TransportLinksText: Allow the use of public transport to nearby accommodation and services
TravelText1: To begin with, choose the way you intend to travel. Then choose the level of fitness that you have.
TravelText2: Easy mode allows you to fill out a few fields about your travel style and which routes you want to travel. Sensible defaults are then used for things like daily distance, accommodation preferences, must-see stops and the like. Detailed mode allows you to fine-tune your preferences in terms of distance, accommodation, where to stop and so on. However, the level of detail can be quite complex. Use easy mode to start with and then uncheck this box to allow more detail once you are familiar with the system.
TravelBottom: Be careful with fitness. Normal is normal for a young walker with plenty of training; someone who can walk three hours at 5km/hr without tiring. If you have any doubts, choose Unfit.
TravelTitle: Travel Style and Fitness

