AccommodationPreferencesLabel: Accommodation Preferences
AppName: De Calixtinus
BackLabel: Back
CaminoPlannerLabel: The Camino Planner
CaminoText: Select the Camino you wish to walk from the following options. Many caminos have variations and alternative routes that you can choose on the next screen.
CaminoTitle: Select Camino
DayServicePreferencesLabel: Preferred Services during Day
DistancePreferencesLabel: Distance Preferences
ExcludedLabel: Locations not to stop at
FinishLocationLabel: Trip End
FitnessText: To begin with, choose the way you intend to travel. Then choose the level of fitness that you have.
FitnessBottom: Be careful with fitness. Normal is normal for a young walker with plenty of training; someone who can walk three hours at 5km/hr without tiring. If you have any doubts, choose Unfit.
FitnessTitle: Travel Style and Fitness
ForbiddenStopsLabel: Forbidden Stops
HelpTitle: Help
HomeText: Welcome to De Calixtinus. If you are planning to walk the Camino Santiago, this site allows you to develop a set of daily stages tailored to your level of fitness and preferences in terms of accomodation, food etc. To begin, press the Start button below.
InvalidCamino: Invalid camino
InvalidStep: Invalid preferences step
MoreInformation: More Information
NextLabel: Next
RangeTitle: Distance and Time Preferences
RangeText: Select the ranges that you will accept for both distance travelled over a day (in km) and time takens (in hours). The ranges are absolute minimum, preferred lower bound, target, preferred upper bound and absolute maximum.
RequiredStopsLabel: Required Stops
RoutePreferencesLabel: Routes
RoutesText: Select the route variants that you wish to walk. The standard route is always selected. Some routes require other routes or cannot be done in conjunction with other routes.
RoutesTitle: Select Routes
SelectCamino: Select a camino
SelectFitness: Select a fitness level
SelectTravel: Select a travel type
ServicesText: Select the cost for stopping at the end of the day and the desired accomodation and services at the end of the day and throughout the day. All preferences are measured in kilometres of walking and represent the amount you would walk extra to avoid a type of accomodation or get a service.
ServicesTitle: Select the Day's Travel Preferences
StartLabel: Start!
StartLocationLabel: Trip Start
StopPreferencesLabel: Day's-end Cost
StopServicePreferencesLabel: Preferred Services at Day's End
StopsLabel: Locations to stop at
StopsText: Select locations where you must stop at the end of a day and locations that you do not wish to stop at.
StopsTitle: Required and Excluded Stops
SuggestedLabel: Suggested
TestMessage: Example only for testing
TimePreferencesLabel: Time Preferences

