AboutLabel: Sobre
AccessTitle: Acceso
AccessibleTitle: Accesible
AccommodationLabel: Alojamiento
AccommodationPenanceLabel: Alojamiento
AccommodationPreferencesLabel: Preferencias de Alojamiento
AirportDescription: Aeropuerto, aeródromo o campo de aviación
AirportTitle: Aeropuerto
AlwaysOpenLabel: Siempre abierto
AfterText: después
ArtworkDescription: Una pieza de arte
ArtworkTitle: Arte
AscentLabel: Ascenso
AscentMsg ascent: Ascenso ^{formatHeight sou ascent}
AustereTitle: Austero
BankTitle: Banco
BeachDescription: Una playa (mar o río)
BeachTitle: Playa
BedlinenTitle: Ropa de cama
BeforeText: antes
BicycleRepairTitle: Reparación de bicicletas
BicycleStorageTitle: Aparcamiento de bicicletas
BoatTitle: Barco/Canoa (remo)
BreakfastTitle: Desayuno
BridgeDescription: Un puente que actúa como punto de referencia o punto de interés
BridgeTitle: Puente
BusTitle: Bus
CalendarTitle: Calendario
CampGroundTitle: Zona de campamento
CaminoLabel: Camino
CampingTitle: Campamento
CampSiteTitle: Campamento-zona
CasaRuralTitle: Casa Rural/Quinta
CasualTitle: Casual
CathedralDescription: Una catedral, basílica, santuario o templo religioso
CathedralTitle: Catedral
ChurchDescription: Una iglesia o capilla
ChurchTitle: Iglesia
CityDescription: Una gran área urbana con múltiples opciones de servicios y alojamiento
CityTitle: Ciudad
ClosedDayText: Día cerrado
ClosedText: cerrado
CloseLabel: Cerrar
ComfortableTitle: Cómodo
ComfortLabel: Comodidad
CopyLinkTitle: Copiar enlace
CrossDescription: Un crucifijo al borde del camino
CrossTitle: Cruz
CulturalPoiTitle: Cultural
CyclingTitle: Ciclismo
CyclePathTitle: Ciclovía (solo bicicletas)
DailyLabel: Diario
DateLabel: Fecha
DayLabel: Día
DaysElapsedMsg d: #{sformat int d} Total de días
DayServicePreferencesLabel: Servicios diurnos no prestados
DayServicesPenanceLabel: Servicios no prestados (día)
DaysWalkingMsg d: #{sformat int d} días caminando
DayText: día
DescentLabel: Descenso
DescentMsg descent: Descenso ^{formatHeight sou descent}
DirectionsTitle: Direcciones
DinnerTitle: Cena
DistanceAdjustLabel: Ajuste de distancia
DistanceMsg actual effort transport perceived: Distancia ^{formatDistance sou actual} #
 (Se siente como ^{formatMaybeDistance sou perceived}#
 $if transport > 0
   \, ^{formatDistance sou transport} transporte#
 \)
DistanceFormatted distance: ^{formatDistance sou distance}
DistanceLabel: Distancia
DistancePenanceLabel: Distancia
DistancePreferencesLabel: Preferencias de Distancia (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DistancePreferencesPerceivedLabel: Preferencias de distancia percibidas (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DoubleTitle: Doble
DoubleWcTitle: Doble con baño
DownloadKmlTitle: Descargar KML
DownloadSpreadsheetTitle: Descargar Excel
DryerTitle: Secadora de ropa
ElevationFormatted elev: ^{formatHeight sou elev}
ElevationLabel: Altura (#{U.unitSymbol (U.preferredUnit sou U.Elevation)})
EventsLabel: Eventos
ExceptText: excepción
ExcludedStopsLabel: Paradas excluídas
FailureLabel: Falla
FarmlandDescription: Granjas, invernaderos, pastos, etc.
FarmlandTitle: Granjas
FatiguePenanceLabel: Cansancio
FerryTitle: Embarcación
FestivalEventTitle: Festival
FinishDateLabel: Fecha de finalización
FinishLocationLabel: Ubicación final
FitnessLabel: Aptitud física
FitTitle: En forma
FoodEventTitle: Comida
FountainDescription: Una fuente o manantial, ya sea una gran fuente decorativa o una fuente de agua
FountainTitle: Fuente
FromLabel: Desde
FrugalTitle: Economizar
GiteTitle: Gîtes d'Étape (Albergue francés)
GroceriesTitle: Alimentos
GuestHouseTitle: Casa de invitados
HalfBoardTitle: Media pensión
HandwashTitle: Lavado de manos
HazardDescription: Un cruce de carretera, puente, pendiente, etc., que requiere precaución
HazardTitle: Peligro
HeatingTitle: Calefacción
HelpLabel: Ayuda
HistoricalPoiTitle: Histórico
HistoricalDescription: Un sitio histórico, un yacimiento arqueológico, una ruina u otro punto de interés histórico
HistoricalTitle: Sitio histórico
HolidayEventTitle: Feriado
HolidaysLabel: Feriados
HomeStayTitle: Permanecer en casa
HostelTitle: Hostel
HotelTitle: Hotel
HoursTitle: Horas
HouseTitle: Casa
IdentifierLabel: ID
IndustryTitle: Industrial
IndustryDescription: Un área industrial o una gran fábrica
InformationLabel: Información
InformationTitle: Información
InformationDescription: Información sobre los datos de origen utilizados para generar este plan
InformationPointDescription: Una oficina de turismo local, guía, etc., no específicamente orientada a peregrinos
InformationPointTitle: Punto de información
IntersectionDescription: Un punto donde se cruzan caminos o senderos
IntersectionTitle: Intersección
JourneyLabel: Viaje
JunctionTitle: Unión
JunctionDescription: Un punto de unión o bifurcación entre dos rutas o caminos
KeyLabel: Llave
KitchenTitle: Cocina
LatitudeLabel: Latitud
LegendLabel: Leyenda
LegPenanceMsg pen: +^{formatPenance sou True pen}
LinkOut: Más información
LocationLabel: Ubicación
LocationPenanceLabel: Ubicación
LocationPreferencesLabel: Preferencia de Ubicación
LocationsLabel: Ubicaciones
LockersTitle: Casilleros
LongitudeLabel: Longitud
LookoutDescription: Un mirador o vista panorámica
LookoutTitle: Mirador
LuxuriousTitle: Lujoso
MapLabel: Mapa
MassEventTitle: Misa
MattressTitle: Colchón
MedicalTitle: Médico
MiscPenanceLabel: Otro
MonasteryDescription: Un monasterio o claustro, a menudo con un hospicio anexo
MonasteryTitle: Monasterio
MunicipalDescription: Una plaza pública, un mercado, un ayuntamiento u otro edificio municipal
MunicipalTitle: Municipal
MuseumDescription: Un museo o galería
MuseumTitle: Museo/galería
MusicEventTitle: Música
NaturalPoiTitle: Natural
NaturalDescription: Un parque natural o área de belleza natural, así como grandes accidentes geográficos como montañas
NaturalTitle: Parque natural
NormalTitle: Normal
NotesLabel: Notas
OpenHoursTitle: Horario de atención
OpenText: open
ParkDescription: Un parque o jardín
ParkTitle: Parque
PathLabel: Camino
PeakDescription: Cima o paso de montaña
PeakTitle: Cima/paso de montaña
PenanceFormatted showZero pen: ^{formatPenance sou showZero pen}
PenanceFormattedPlain showZero pen: ^{formatPenancePlain sou showZero pen}
PenanceMsg pen: Penitencia ^{formatPenance sou True pen}
PenanceReject: Rechazado
PenanceSummaryLabel: Penitencia
PerceivedDistanceLabel: Distancia percibida
PerformanceEventTitle: Rendimiento
PersistentLinkTitle: Enlace permanente
PetsTitle: Mascotas
PharmacyTitle: Farmacia
PilgrimageLabel: Peregrinaje
PilgrimAlbergueTitle: Albergue de peregrinos
PilgrimMassEventTitle: Misa del peregrino
PilgrimPoiTitle: Peregrino(a)
PilgrimResourceDescription: Oficina de peregrinos, punto de descanso, etc., específicamente orientado a los peregrinos
PilgrimResourceTitle: Recurso para peregrinos
PilgrimTitle: Peregrinos
PlaceholderLabel: Marcador de posición
PlanLabel: Plan
PoiDescription: Un punto de referencia o punto de interés genérico
PoiLabel: Punto de interés
PoisLabel: Puntos de interés
PoiTitle: Localidad
PoolTitle: Piscina
PrayerTitle: Rezo/oración
PreferencesLabel: Preferencias
PrivateAlbergueTitle: Albergue privado
ProgramLabel: Programa
PromontoryDescription: Un risco, acantilado o cabo
PromontoryTitle: Risco/Cabo
PublicHolidayText: Día festivo
QuadrupleTitle: Habitación cuádruple
QuadrupleWcTitle: Habitación cuádruple con baño
RefugeTitle: Refugio
RegionLabel: Región
RegionsLabel: Regiones
RecreationPoiTitle: Recreación
ReligiousEventTitle: Ceremonia religiosa
ReligiousPoiTitle: Religioso
RequiredStopsLabel: Paradas obligatorias
RestaurantTitle: Restaurante
RestDaysLabel: Días de descanso
RestLocationPreferencesLabel: Preferencias de ubicación de descanso
RestPressureLabel: Presión en reposo
RestPenanceLabel: Descanso
RestpointLabel: Punto de descanso
RestpointsLabel: Puntos de descanso
RestPointsPenanceLabel: Puntos de descanso
RestPreferencesLabel: Preferencias de descanso (días de viaje)
RestPressurePenanceLabel: Presión en reposo
RoadTitle: Camino/sendero
RouteLabel: Ruta
RouteServicesPreferencesLabel: Servicios faltantes en la ruta
RoutesLabel: Rutas
ServicesLabel: Servicios
ServicesPreferencesLabel: Servicios faltantes
SharedTitle: Compartido
ShopDescription: Tienda destacada o útil
ShopTitle: Tienda
ShowLabelsTitle: Mostrar las etiquetas del Camino y de la ruta en el mapa
ShowOnMapTitle: Mostrar en el mapa
SingleTitle: Individual
SIUnitsTitle: Kilómetros, metros, horas
SleepingBagTitle: Saco de dormir
StablesTitle: Establos
StageLabel: Escenario
StagesMsg d: ^{formatStages d}
StartDateLabel: Fecha de inicio
StartLabel: ¡Comenzar!
StartLocationLabel: Ubicación de inicio
StationDescription: Una estación de tren o bus
StationTitle: Estación
StatueDescription: Una estatua, un bajorrelieve, etc.
StatueTitle: Estatua
StockpointLabel: Punto de abastecimiento
StopLabel: Parada
StopPenanceLabel: Parada
StopServicesPenanceLabel: Servicios faltantes (Parada)
StopPreferencesLabel: Costo de la parada
SuperFitTitle: Muy en forma
TableLabel: Mesa
TheatreDescription: Un teatro, una ópera o una sala de conciertos.
TheatreTitle: Teatro
TimeAdjustLabel: Modificación de hora
TimeFormatted time: ^{formatHours sou time}
TimeMsg mtime meffort mtransport mpoi: Más de ^{formatMaybeHours sou mtime} #
  $case (mtransport, mpoi)
    $of (Nothing, Nothing)
    $of (Just t, Nothing)
      (^{formatHours sou t} transporte)
    $of (Nothing, Just p)
      (^{formatHours sou p} paradas)
    $of (Just t, Just p)
      (^{formatHours sou t} transporte, ^{formatHours sou p} paradas)
TimeLabel: Tiempo
TimePenaltyLabel: Penalización de tiempo
TimePreferencesLabel: Preferencias de tiempo (#{U.unitSymbol (U.preferredUnit sou U.Time)})
ToggleDetailTitle: Mostrar/ocultar detalles adicionales
ToLabel: A
TowelsTitle: Toallas
TownDescription: Localidad mediana con la mayoría de los servicios y diversas opciones de alojamiento
TownTitle: Pueblo
TrailTitle: Sendero (sólo para senderistas)
TrainTitle: Tren
TransportLinksLabel: Conexiones de transporte
TravelLabel: Estimación de viaje
TripFinishLabel: Final del viaje
TripStartLabel: Inicio del viaje
TripleTitle: Habitación triple
TripleWcTitle: Habitación triple con baño
TypeLabel: Tipo
UnfitTitle: Fuera de forma
UnitsLabel: Unidades
UnusedLabel: No usado
USUnitsTitle: Millas, pies, horas
VeryFitTitle: Muy en format
VeryUnfitTitle: Poco en forma
VillageDescription: Pequeña localidad rural con servicios y alojamientos limitados
VillageTitle: Aldea
WalkingTitle: Caminata
WalkingNaismithTitle: Caminando (resistencia alta)
WarningTitle: Peligro
WashingMachineTitle: Lavadora
WaterBodyDescription: Lago, embalse, río, canal, etc.
WaterBodyTitle: Agua
WaypointLabel: Punto de referencia
WharfDescription: Un muelle, embarcadero o pantalán que conecta con un barco.
WharfTitle: Muelle
WiFiTitle: WiFi/conexión a internet
WineryDescription: Una bodega o almacén de vino
WineryTitle: Bodega
