AboutLabel: Sobre
AboutPageLabel: Acerca De Calixtinus
AboutPageTitle: De Calixtinus
AcceptLabel: Aceptar
AcceptDisclaimerLabel: Acepto el uso de cookies y el estado de prueba
AcceptDisclaimerRequired: Debes aceptar las condiciones antes de continuar
AccessTitle: Acceso
AccessibleTitle: Accesible
AccommodationLabel: Alojamiento
AccommodationPenanceLabel: Alojamiento
AccommodationPreferencesLabel: Preferencias de alojamiento
AfterText: después
AirportDescription: Aeropuerto, aeródromo o campo de aviación
AirportTitle: Aeropuerto
AlwaysOpenLabel: Siempre abierto
AppName: De Calixtinus
ArtworkDescription: Una pieza de arte
ArtworkTitle: Arte
AscentLabel: Ascenso
AscentMsg ascent: Ascenso ^{formatHeight sou ascent}
AustereTitle: Austero
BackLabel: Atrás
BankTitle: Banco
BeachDescription: Una playa (mar o río)
BeachTitle: Playa
BedlinenTitle: Ropa de cama
BeforeText: antes
BicycleRepairTitle: Reparación de bicicletas
BicycleStorageTitle: Aparcamiento de bicicletas
BoatTitle: Barco/Canoa (remo)
BreakfastTitle: Desayuno
BridgeDescription: Un puente que actúa como punto de referencia o punto de interés
BridgeTitle: Puente
BusTitle: Bus
CalendarTitle: Calendario
CaminoSelectTitle: Seleccionar Camino
CaminoLabel: Camino
CaminosLabel: Caminos
CaminoText: Selecciona el Camino que deseas recorrer entre las siguientes opciones. Muchos caminos tienen variantes y rutas alternativas que podrás elegir en la siguiente pantalla.
CampGroundTitle: Zona de campamento
CampingTitle: Campamento
CampSiteTitle: Campamento-zona
CasaRuralTitle: Casa Rural/Quinta
CasualTitle: Casual
CathedralDescription: Una catedral, basílica, santuario o templo religioso
CathedralTitle: Catedral
ChurchDescription: Una iglesia o capilla
ChurchTitle: Iglesia
CityDescription: Una gran área urbana con múltiples opciones de servicios y alojamiento
CityTitle: Ciudad
ClosedDayLabel region@Text: Día cerrado (^{renderLocalisedRegion config sou locales region})
ClosedDayText: Día cerrado
ClosedText: cerrado
CloseLabel: Cerrar
ComfortableTitle: Cómodo
ComfortLabel: Comodidad
CopyLinkTitle: Copiar enlace
CrossDescription: Un crucifijo al borde del camino
CrossTitle: Cruz
CulturalPoiTitle: Cultural
CyclingTitle: Ciclismo
CyclePathTitle: Ciclovía (solo bicicletas)
DailyLabel: Diario
DateLabel: Fecha
DayLabel: Día
DaysElapsedMsg d: #{sformat int d} Total de días
#DayServicePreferencesLabel: Servicios diurnos no prestados
DayServicePreferencesLabel: Servicios preferidos durante el día
DayServicesPenanceLabel: Servicios no prestados (día)
DaysWalkingMsg d: #{sformat int d} días caminando
DayText: día
DescentLabel: Descenso
DescentMsg descent: Descenso ^{formatHeight sou descent}
DirectionsTitle: Direcciones
DinnerTitle: Cena
DistanceAdjustLabel: Ajuste de distancia
DistanceFormatted distance: ^{formatDistance sou distance}
DistanceLabel: Distancia
DistanceMsg actual effort transport perceived: Distancia ^{formatDistance sou actual} #
 (Se siente como ^{formatMaybeDistance sou perceived}#
 $if transport > 0
   \, ^{formatDistance sou transport} transporte#
 \)
DistancePenanceLabel: Distancia
DistancePreferencesLabel: Preferencias de distancia (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DistancePreferencesPerceivedLabel: Preferencias de distancia percibidas (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
DoubleTitle: Doble
DoubleWcTitle: Doble con baño
DownloadKmlTitle: Descargar KML
DownloadSpreadsheetTitle: Descargar Excel
DryerTitle: Secadora de ropa
EasyMode: Modo fácil
EasyModeText: El modo fácil reduce la cantidad de decisiones que debes tomar y selecciona opciones predeterminadas adecuadas para la mayoría de las cosas.
ElevationFormatted elev: ^{formatHeight sou elev}
ElevationLabel: Altura (#{U.unitSymbol (U.preferredUnit sou U.Elevation)})
EventsLabel: Eventos
ExceptText: excepción
ExcludedLabel: Lugares donde no detenerse
ExcludedStopsLabel: Paradas excluídas
FailureLabel: Falla
FarmlandDescription: Granjas, invernaderos, pastos, etc.
FarmlandTitle: Granjas
FatiguePenanceLabel: Cansancio
FerryTitle: Embarcación
FestivalEventTitle: Festival
FinishDateLabel: Fecha de finalización
#FinishLocationLabel: Ubicación final
FinishLocationLabel: Final del viaje
FitnessLabel: Aptitud física
FitTitle: En forma
FoodEventTitle: Comida
ForbiddenStopsLabel: Paradas prohibidas
FountainDescription: Una fuente o manantial, ya sea una gran fuente decorativa o una fuente de agua
FountainTitle: Fuente
FromLabel: Desde
FrugalTitle: Economizar
GiteTitle: Gîtes d'Étape (Albergue francés)
GroceriesTitle: Alimentos
GuestHouseTitle: Casa de invitados
HalfBoardTitle: Media pensión
HandwashTitle: Lavado de manos
HazardDescription: Un cruce de carretera, puente, pendiente, etc., que requiere precaución
HazardTitle: Peligro
HeatingTitle: Calefacción
HelpLabel: Ayuda
HelpPageTitle: Ayuda General
HelpPopupTitle: Ayuda
HistoricalPoiTitle: Histórico
HistoricalDescription: Un sitio histórico, un yacimiento arqueológico, una ruina u otro punto de interés histórico
HistoricalTitle: Sitio histórico
HolidayEventTitle: Feriado
HolidaysLabel: Feriados
HomePageLabel: Inicio
HomePageText1: Bienvenido a De Calixtinus.
HomePageText2: Si estás planeando recorrer el Camino de Santiago, este sitio te permite desarrollar un conjunto de etapas diarias adaptadas a tu nivel físico y preferencias en términos de alojamiento, comida, etc. El planificador está diseñado para darte un conjunto globalmente óptimo de etapas, ampliando algunas y reduciendo otras para ofrecerte el mejor viaje posible.
HomePageText3: Para iniciar pulse el botón ¡Comenzar! que aparece a continuación.
HomeStayTitle: Permanecer en casa
HostelTitle: Hostel
HotelTitle: Hotel
HoursTitle: Horas
HouseTitle: Casa
IndustryDescription: Un área industrial o una gran fábrica
IndustryTitle: Industrial
InformationDescription: Información sobre los datos de origen utilizados para generar este plan
InformationLabel: Información
InformationPointDescription: Una oficina de turismo local, guía, etc., no específicamente orientada a peregrinos
InformationPointTitle: Punto de información
InformationTitle: Información
IntersectionDescription: Un punto donde se cruzan caminos o senderos
IntersectionTitle: Intersección
InvalidCamino: Camino inválido
InvalidStep: Paso de preferencia no válido
JourneyLabel: Viaje
JunctionDescription: Un punto de unión o bifurcación entre dos rutas o caminos
JunctionTitle: Unión
KeyLabel: Llave
KitchenTitle: Cocina
LatitudeLabel: Latitud
LegendLabel: Leyenda
LegPenanceMsg pen: +^{formatPenance sou True pen}
LinkOut: Más información
LocationLabel: Ubicación
LocationPenanceLabel: Ubicación
LocationPreferencesLabel: Preferencias de ubicación
LocationsLabel: Ubicaciones
LockersTitle: Casilleros
LongitudeLabel: Longitud
LookoutDescription: Un mirador o vista panorámica
LookoutTitle: Mirador
LuxuriousTitle: Lujoso
MapLabel: Mapa
MapTitle: Mapa de todos los caminos
MassEventTitle: Misa
MattressTitle: Colchón
MedicalTitle: Médico
MetricLabel: Conversión métrica
MetricTitle: Conversión métrica/imperial
MiscPenanceLabel: Otro
MonasteryDescription: Un monasterio o claustro, a menudo con un hospicio anexo
MonasteryTitle: Monasterio
MoreInformation: Más información
MunicipalDescription: Una plaza pública, un mercado, un ayuntamiento u otro edificio municipal
MunicipalTitle: Municipal
MuseumDescription: Un museo o galería
MuseumTitle: Museo/galería
MusicEventTitle: Música
NaturalDescription: Un parque natural o área de belleza natural, así como grandes accidentes geográficos como montañas
NaturalPoiTitle: Natural
NaturalTitle: Parque natural
NextLabel: Siguiente
NormalTitle: Normal
NotesLabel: Notas
OpenHoursTitle: Horario de atención
OpenText: open
ParkDescription: Un parque o jardín
ParkTitle: Parque
PathLabel: Camino
PeakDescription: Cima o paso de montaña
PeakTitle: Cima/paso de montaña
PenanceMsg pen: Penitencia ^{formatPenance sou True pen}
PenanceReject: Rechazado
PenanceSummaryLabel: Penitencia
PerceivedDistanceLabel: Distancia percibida
PerformanceEventTitle: Rendimiento
PersistentLinkTitle: Enlace permanente
PetsTitle: Mascotas
PharmacyTitle: Farmacia
PilgrimageLabel: Peregrinaje
PilgrimAlbergueTitle: Albergue de peregrinos
PilgrimMassEventTitle: Misa del peregrino
PilgrimPoiTitle: Peregrino(a)
PilgrimResourceDescription: Oficina de peregrinos, punto de descanso, etc., específicamente orientado a los peregrinos
PilgrimResourceTitle: Recurso para peregrinos
PilgrimTitle: Peregrinos
PlaceholderLabel: Marcador de posición
PlanKmlLabel: Plan (KML)
PlanKmlTitle: Generar un plan como archivo KML compatible con Google Earth
PlanLabel: Plan
PlanTitle: Generar y mostrar un plan
PlanXlsxLabel: Plan (Xlsx)
PlanXlsxTitle: Generar un plan como archivo Xlsx compatible con aplicaciones de hojas de cálculo
PoiDescription: Un punto de referencia o punto de interés genérico
PoiLabel: Punto de interés
PoisLabel: Puntos de interés
PoiText: Selecciona los puntos de interés importantes en los que planeas detenerte durante el viaje. Estas paradas se incluirán en el tiempo de planificación.
PoiTitle: Localidad
# PoiTitle: Preferencias de puntos de interés
PoolTitle: Piscina
PrayerTitle: Rezo/oración
PreferencesLabel: Preferencias
PreferredRestPointsLabel: Puntos de descanso preferidos
PrivateAlbergueTitle: Albergue privado
ProgramLabel: Programa
PromontoryDescription: Un risco, acantilado o cabo
PromontoryTitle: Risco/Cabo
PublicHolidayLabel region@Text: Día festivo ^{renderLocalisedRegion config sou locales region}
PublicHolidayText: Día festivo
QuadrupleTitle: Habitación cuádruple
QuadrupleWcTitle: Habitación cuádruple con baño
RangeTitle: Preferencias de distancia y tiempo
RangeText: Selecciona los rangos que prefieres para la distancia recorrida cada día (en km) y el tiempo dedicado a caminar (en horas). También indica cuántos días te gustaría caminar antes de tomar un día de descanso (día libre). Los rangos se definen mediante un mínimo absoluto, un límite inferior preferido, un objetivo, un límite superior preferido y un máximo absoluto.
RefugeTitle: Refugio
RegionLabel: Región
RegionsLabel: Regiones
RecreationPoiTitle: Recreación
ReligiousEventTitle: Ceremonia religiosa
ReligiousPoiTitle: Religioso
RequiredStopsLabel: Paradas obligatorias
RestaurantTitle: Restaurante
RestDaysLabel: Días de descanso
#RestLocationPreferencesLabel: Preferencias de ubicación de descanso
RestLocationPreferencesLabel: Preferencias de ubicación para descanso
RestPenanceLabel: Descanso
RestpointLabel: Punto de descanso
RestpointsLabel: Puntos de descanso
RestPointsPenanceLabel: Puntos de descanso
#RestPreferencesLabel: Preferencias de descanso (días de viaje)
RestPreferencesLabel: Preferencias de descanso (#{U.unitSymbol (U.preferredUnit sou U.Calendar)})
RestPressureLabel: Presión de reposo (#{U.unitSymbol (U.preferredUnit sou U.Distance)})
RestPressurePenanceLabel: Presión en reposo
RestServicePreferencesLabel: Servicios de descanso
RoadTitle: Camino/sendero
RouteLabel: Ruta
RoutePreferencesLabel: Rutas
RouteServicesPreferencesLabel: Servicios faltantes en la ruta
RoutesLabel: Rutas
RoutesText: Selecciona las variantes de ruta que deseas recorrer. La ruta estándar siempre estará seleccionada. Algunas rutas requieren otras rutas o no pueden realizarse junto con otras.
RoutesTitle: Seleccionar rutas
RangeTitle: Preferencias de distancia y tiempo
RangeText: Selecciona los rangos que prefieres para la distancia recorrida cada día (en km) y el tiempo dedicado a caminar (en horas). También indica cuántos días te gustaría caminar antes de tomar un día de descanso (día libre). Los rangos se definen mediante un mínimo absoluto, un límite inferior preferido, un objetivo, un límite superior preferido y un máximo absoluto.
RequiredStopsLabel: Paradas obligatorias
SelectCamino: Selecciona un Camino
SelectComfort: Selecciona un nivel de comodidad
SelectFitness: Selecciona un nivel físico
SelectPoiCategories: Selecciona puntos de interés que podrías visitar
SelectTravel: Selecciona un tipo de viaje
SelectUnits: Selecciona unidades
ServicesLabel: Servicios
ServicesPreferencesLabel: Servicios faltantes
ServicesRestText: Selecciona las preferencias de ubicación, alojamiento y servicios para una parada de descanso. Las paradas de descanso son lugares donde puedes tomarte un día libre para recuperarte, reabastecerte, hacer turismo y prepararte para la siguiente etapa del camino.
ServicesRestTitle: Selecciona preferencias de paradas de descanso
ServicesStockText: Selecciona las preferencias de ubicación, alojamiento y servicios para un día de abastecimiento. Los días de abastecimiento son aquellos en los que esperas no tener muchas facilidades disponibles al día siguiente, porque muchos de los servicios que necesitas estarán cerrados. Por ejemplo, si el día siguiente es domingo o festivo, deberás asegurarte de haber comprado comida con anticipación.
ServicesStockTitle: Seleccionar preferencias de parada para abastecimiento
ServicesStopText: Seleccionar preferencias de ubicación, alojamiento y servicios para el final del día.
ServicesStopTitle: Seleccionar preferencias de viaje para el día.
ServicesText2: Todas las preferencias se miden en kilómetros caminados y representan la distancia extra que caminarías para obtener algo que deseas.
SharedTitle: Compartido
ShopDescription: Tienda destacada o útil
ShopTitle: Tienda
ShowLabelsTitle: Mostrar las etiquetas del Camino y de la ruta en el mapa
ShowOnMapTitle: Mostrar en el mapa
ShowPreferencesText: Si estás conforme con estas preferencias, puedes generar un plan. De lo contrario, utiliza el botón Atrás para cambiar tus elecciones.
ShowPreferencesTitle: Revisar preferencias
SingleTitle: Individual
SIUnitsTitle: Kilómetros, metros, horas
SleepingBagTitle: Saco de dormir
StablesTitle: Establos
StageLabel: Escenario
StagesMsg d: ^{formatStages d}
StartDateLabel: Fecha de inicio
StartLabel: ¡Comenzar!
StartLocationLabel: Ubicación de inicio
StartLocationLabel: Inicio del viaje
StartText: Selecciona el punto de inicio y final de tu viaje.
StartTitle: Puntos de inicio y final
StationDescription: Una estación de tren o bus
StationTitle: Estación
StatueDescription: Una estatua, un bajorrelieve, etc.
StatueTitle: Estatua
StockpointLabel: Punto de abastecimiento
StopLabel: Parada
StopPenanceLabel: Parada
StopPreferencesLabel: Servicios faltantes (Parada)
#StopPreferencesLabel: Final del día
StopPreferencesText: El final del día representa el proceso de detenerse y acomodarse para pasar la noche.
StopServicePreferencesLabel: Servicios preferidos al final del día
StopServicesPenanceLabel: Servicios faltantes (Parada)
StopsLabel: Lugares donde detenerse
StopsText: Selecciona lugares donde debes detenerte al final del día y lugares donde no deseas detenerte.
StopsTitle: Paradas obligatorias y excluidas
SuggestedLabel: Sugerido
SuperFitTitle: Muy en forma
TableLabel: Mesa
TestMessage: Actualmente en pruebas, consulta la página Acerca de
TheatreDescription: Un teatro, una ópera o una sala de conciertos.
TheatreTitle: Teatro
TimeAdjustLabel: Modificación de hora
TimeFormatted time: ^{formatHours sou time}
TimeLabel: Tiempo
TimeMsg mtime meffort mtransport mpoi: Más de ^{formatMaybeHours sou mtime} #
  $case (mtransport, mpoi)
    $of (Nothing, Nothing)
    $of (Just t, Nothing)
      (^{formatHours sou t} transporte)
    $of (Nothing, Just p)
      (^{formatHours sou p} paradas)
    $of (Just t, Just p)
      (^{formatHours sou t} transporte, ^{formatHours sou p} paradas)
TimePenaltyLabel: Penalización de tiempo
TimePreferencesLabel: Preferencias de tiempo (#{U.unitSymbol (U.preferredUnit sou U.Time)})
ToggleDetailTitle: Mostrar/ocultar detalles adicionales
ToLabel: A
TowelsTitle: Toallas
TownDescription: Localidad mediana con la mayoría de los servicios y diversas opciones de alojamiento
TownTitle: Pueblo
TrailTitle: Sendero (sólo para senderistas)
TrainTitle: Tren
TransportLinksLabel: Conexiones de transporte
TransportLinks: Usar conexiones de transporte
TransportLinksText: Permitir el uso de transporte público hacia alojamientos y servicios cercanos
TravelBottom: Ten cuidado con la condición física. Lo normal es para un joven que camina con suficiente entrenamiento; alguien que puede caminar tres horas a 5 km/h sin cansarse. Si tienes alguna duda, elige "Fuera de forma".
TravelLabel: Estimación de viaje
TravelText1: Para comenzar, elige la manera en que deseas viajar. Luego selecciona el nivel físico que tienes.
TravelText2: El modo fácil te permite completar algunos campos sobre tu estilo de viaje y las rutas que deseas recorrer. Se utilizan valores predeterminados sensatos para aspectos como la distancia diaria, las preferencias de alojamiento, las paradas imprescindibles, etc. El modo detallado te permite ajustar con precisión tus preferencias en cuanto a distancia, alojamiento, paradas, etc. Sin embargo, el nivel de detalle puede ser bastante complejo. Usa el modo fácil para empezar y luego desmarca esta casilla para permitir un mayor nivel de detalle una vez que te familiarices con el sistema.
TravelTitle: Estilo de viaje y condición física
TripFinishLabel: Final del viaje
TripStartLabel: Inicio del viaje
TripleTitle: Habitación triple
TripleWcTitle: Habitación triple con baño
TypeLabel: Tipo
UnfitTitle: Fuera de forma
UnitsLabel: Unidades
UnusedLabel: No usado
USUnitsTitle: Millas, pies, horas
VeryFitTitle: Muy en format
VeryUnfitTitle: Muy fuera de forma
VillageDescription: Pequeña localidad rural con servicios y alojamientos limitados
VillageTitle: Aldea
WalkingNaismithTitle: Caminando (resistencia alta)
WalkingTitle: Caminata
WarningTitle: Peligro
WashingMachineTitle: Lavadora
WaterBodyDescription: Lago, embalse, río, canal, etc.
WaterBodyTitle: Agua
WaypointLabel: Punto de referencia
WharfDescription: Un muelle, embarcadero o pantalán que conecta con un barco.
WharfTitle: Muelle
WiFiTitle: WiFi/conexión a internet
WineryDescription: Una bodega o almacén de vino
WineryTitle: Bodega
